---
- name: Run preparations
  gather_facts: false
  hosts: ceph
  become: true

  vars_files:
    - /opt/configuration/environments/configuration.yml
    - /opt/configuration/environments/images.yml
    - /opt/configuration/environments/secrets.yml
    - /opt/configuration/environments/ceph/configuration.yml
    - /opt/configuration/environments/ceph/images.yml
    - /opt/configuration/environments/ceph/secrets.yml

  roles:
    - ceph-defaults
    - ceph-facts

- name: Apply role ceph-osd
  gather_facts: false
  hosts: ceph-osd
  become: true

  vars_files:
    - /opt/configuration/environments/configuration.yml
    - /opt/configuration/environments/images.yml
    - /opt/configuration/environments/secrets.yml
    - /opt/configuration/environments/ceph/configuration.yml
    - /opt/configuration/environments/ceph/images.yml
    - /opt/configuration/environments/ceph/secrets.yml

  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-docker-common
    - ceph-config
    - ceph-osd
